# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('weight', models.IntegerField()),
                ('color', models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('White', 'White'), ('Black', 'Black'), ('Golden', 'Golden'), ('Brown', 'Brown'), ('Others', 'Others')], max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Appliances', 'Appliances'), ('Fashion', 'Fashion'), ('Sports, Fitness and Outdoor', 'Sports, Fitness and Outdoor'), ('Motors and Accessories', 'Motors and Accessories'), ('Books', 'Books'), ('Others', 'Others')], max_length=200)),
                ('stock', models.IntegerField()),
                ('description', models.CharField(max_length=400)),
                ('images', models.FileField(upload_to='')),
            ],
        ),
    ]
