# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-04 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_orders_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratings',
            old_name='prod',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='orders',
        ),
        migrations.AddField(
            model_name='ratings',
            name='sentiments',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
