# Generated by Django 3.2 on 2025-05-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20250514_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='ratings',
            field=models.IntegerField(max_length=100),
        ),
    ]
